#ifndef TEXENGINE_ASSETENUM_H_INCLUDED
#define TEXENGINE_ASSETENUM_H_INCLUDED

namespace TEXEngine {
	namespace Asset {

enum TEXENG_LIGHT_TYPE
{
	TEXENG_LIGHT_POINT,			// Point light
	TEXENG_LIGHT_SPOT,			// Spot light
	TEXENG_LIGHT_DIRECTIONAL	// Directional light
};

enum TEXENG_TEXTURE_TYPE
{
	TEXENG_TEXTURE_GENERIC,
	TEXENG_TEXTURE_SPRITE,
	TEXENG_TEXTURE_FONT,
	TEXENG_TEXTURE_COLORMAP,
	TEXENG_TEXTURE_HEIGHTMAP,
	TEXENG_TEXTURE_NORMALMAP1,
	TEXENG_TEXTURE_NORMALMAP2,
	TEXENG_TEXTURE_BLENDMAP
};

enum TEXENG_AUDIO_TYPE
{ 
	TEXENG_AUDIO_FX, 
	TEXENG_AUDIO_MUSIC 
};

enum TEXENG_CAMERA_TYPE
{
	TEXENG_CAMERA_CHASE,
	TEXENG_CAMERA_FPS
};

	} /* namespace Asset */
} /* Namespace TEXEngine */

#endif /* TEXENGINE_ASSETENUM_H_INCLUDED */